# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    api_key_user_provider:
        class: Auto\Bundle\Api2Bundle\Security\ApiKeyUserProvider

    apikey_authenticator:
        class:     Auto\Bundle\Api2Bundle\Security\ApiKeyAuthenticator

    admin.operate_listener:
        class: Auto\Bundle\ManagerBundle\EventListener\OperateListener
        arguments: ["@service_container"]
        tags:
            - { name: doctrine.event_listener, event: postPersist, connection: default }
            - { name: doctrine.event_listener, event: postUpdate, method: postUpdate }
            - { name: doctrine.event_listener, event: postRemove, method: postRemove }
